comments/urls.py
from django.urls import path
from comments.views import add, show_list, get_only_comment, update_comment, delete_comment

app_name = 'comments'

urlpatterns = [
    path('add', add, name='add'),
    path('comments_list', show_list, name='comments_list'),
    path('get_comment/<int:id>/', get_only_comment, name='get_only_comment'),
    path('update_comment/<int:id>/', update_comment, name='update_comment'),
    path('delete_comment/<int:id>/', delete_comment, name='delete_comment'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('comments.urls')),
]

comments/models.py
from django.db import models
from elements.models import Element

# Create your models here.
class Comment(models.Model):
    text = models.TextField()
    date_posted = models.DateField(auto_now_add=True)
    element = models.ForeignKey(Element, related_name='comments', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.text

elements/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.title

class Type(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.title

class Element(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2, default=6.10)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)

comments/forms.py
from django.forms import ModelForm, Textarea
from comments.models import Comment

class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

comments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from comments.models import Comment

from comments.forms import CommentForm


def add(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('comments:comments_list')
    else:
        form = CommentForm()

    return render(request, 'comments/add.html', {'form': form})

def show_list(request):

    if request.method == 'GET':
        comments = Comment.objects.all()
        return render(
            request,
            'comments/comments_list.html',
            {'comments_list': comments}
        )

def get_only_comment(request, id):

    if request.method == 'GET':
        get_comment = Comment.objects.get(id=id)
        return render(
            request,
            'comments/comment_detail.html',
            {'comment_detail': get_comment}
        )

def update_comment(request, id):

    comment = get_object_or_404(Comment, id=id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('comments:comments_list')
    else:
        form = CommentForm(instance=comment)
        return render(
            request,
            'comments/update_comment.html',
            {'form_update': form}
        )

def delete_comment(request, id):

    comment = Comment.objects.filter(id=id)
    comment.delete()

    return redirect('comments:comments_list')

elements/views.py
from django.shortcuts import render

# Create your views here.

comments/templates/comments/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>add</title>
</head>
<body>
    <h1>Page to add</h1>

    <form method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

comments/templates/comments/comment_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comment Detail</title>
</head>
<body>
    <h1>Comment Detail</h1>

    <table border="2">
        <th>Texto</th>
        <th>Dato de Creación</th>
        <tr>
            <td>{{ comment_detail.text }}</td>
            <td>{{ comment_detail.date_posted }}</td>
        </tr>
    </table>
</body>
</html>

comments/templates/comments/comments_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>comments_list</title>
</head>
<body>
    <h1>Comments List</h1>
        <ul>
            {% for comment in comments_list %}
            <li>{{ comment }}
                <a href="{% url 'comments:get_only_comment' comment.id %}">Detalles</a>
                <a href="{% url 'comments:update_comment' comment.id %}">Actualizar</a>
                <a href="{% url 'comments:delete_comment' comment.id %}">Eliminar</a>
            </li>
            {% endfor %}
        </ul>
</body>
</html>

comments/templates/comments/update_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update comment</title>
</head>
<body>

    <h1>Update Comment</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form_update.as_p }}
        <button type="submit">Actualizar</button>
    </form>

</body>
</html>